name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag swiggy:latest
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          docker tag swiggy:latest amansingh12/swiggy:latest
          docker push amansingh12/swiggy:latest
          docker run -dit -p 80:3000 amansingh12/swiggy:latest
          sudo chown $USER:$USER /var/run/docker.sock
          docker ps
